Advertisement iryna
maryna999/premium-watches pull request #12
Opened 2024-05-02 16:39 UTC by cldGryphem

2024-05-03 17:10 UTC, cldGryphem reviewed
added image-set

2024-05-04 10:14 UTC, maryna999 requested changes
Все гуд, лише один маленький нюансик- на десктопі в секції замініть margin-bottom на padding bottom.

2024-05-04 15:26 UTC, cldGryphem reviewed
Виправлений десктоп

2024-05-04 15:27 UTC, cldGryphem reviewed
Виправлений десктоп

2024-05-04 15:40 UTC, cldGryphem reviewed
Виправлено на padding

2024-05-05 16:44 UTC, cldGryphem reviewed
add

2024-05-05 16:47 UTC, maryna999 approved these changes

2024-05-05 16:47 UTC, merged