Reviews hiricheva
maryna999/premium-watches pull request #9
Opened 2024-05-02 12:47 UTC by Vita0609

https://github.com/maryna999/premium-watches/compare/main...reviews-hiricheva?expand=1

2024-05-02 13:10 UTC, maryna999 requested changes
1. В section у вас 2 класи, одного буде достатньо.
2. Замініт alt на 2-му і 3-му зображеннях, бо у вас всі Джони Вакси)))


Решта все, ніби, гуд.

2024-05-03 05:30 UTC, maryna999 requested changes
1. В класі section має бути тільки padding-bottom, решту видаліть.
2.  На зображення 2 і 3 додати додаткові класи (краще різні),  і прописати display: none.
3. В класі reviews-team лишити тільки display: flex; flex-direction: column; align-items: center.
4. Властивість gap: 8px; в класі content-reviews не підходить, бо від зображення до заголовку 24 px.
5. Font-family також зайвий, бо вже прописаний в основних стилях.
6. В content-reviews  властивість padding: 0 20px; зайва.

2024-05-03 09:29 UTC, Vita0609 commented
я виправила все

2024-05-04 10:54 UTC, maryna999 requested changes
Надіслала все в слак)

2024-05-05 17:46 UTC, maryna999 requested changes
Ще трошки)

2024-05-05 19:01 UTC, maryna999 approved these changes

2024-05-05 19:06 UTC, merged